### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by Booteille** [da2x/amp2html#11]
That would be great if we could just check last changes in a changelog instead of checking commits.

Thanks!

**Comment by da2x** [comment]
The change log is maintained on [the home page](https://www.daniel.priv.no/web-extensions/amp2html.html), [IPFS](https://js.ipfs.io/ipns/daniel.priv.no/web-extensions/amp2html.html), [OpenHub](https://www.openhub.net/p/amp2html/rss_articles), on [AMO versions](https://addons.mozilla.org/en-US/firefox/addon/amp2html/versions/), and you can see what has changed from the Recently updated addons page in Firefox itself.
