### ISSUE TITLE
What is the purpose of .amp.cloudflare.com cookie?

### ISSUE THREAD

**Issue by crssi** [da2x/amp2html#12]
Thank you

**Comment by da2x** [comment]
It’s an opt-out cookie that disables auto-AMP-ing of links on third party websites that use Cloudflare Viewer and AML. Meaning you’ll get the original un-AMP-ed links instead of making the extension “un-AMP” them later.
https://amp.cloudflare.com/viewer/optout.html

**Comment by crssi** [comment]
Cool. I guessed right. Thank you for explanation.

How this cookie is to be used, if I browse in container (non default context)?
Containers have no access to default context and in that case cannot access to this cookie (since it is in a default context). Or, I am wrong?

Cheers

**Comment by da2x** [comment]
With advanced features like that, you’ll not be able to take advantage of the opt-out cookie. Other mechanisms in the extension will redirect you to the non-AMP version.
