### ISSUE TITLE
Uploading it to the edge chromium store ?

### ISSUE THREAD

**Issue by aelisya** [da2x/amp2html#15]
Hello i would like to know if you have the intention of uploading this extension to the edge (chromium edition curently in alpha) on the microsoft store ?

Thanks in advance

**Comment by da2x** [comment]
As far as I know, you can go to the extensions page in Edge Anaheim and enable an option to install extensions from the Chrome Store.

That being said, I’m not opposed to distributing it through Microsoft’s Store directly. However, I haven’t been able to locate any developer information on how to do that. It seems its by invitation only?

**Comment by aelisya** [comment]
yes, i'am actually use it on google store, but it would be nice to have it on the Microsoft store too,
I have contacted them, and they said they work on a documentation, it seem's for now, the upload process is linked to the old one (edgeHTML).
If you had said no, I would have asked you for permission to upload it myself when their documentation is ready.

**Comment by da2x** [comment]
Just notify me when they open up the process and publish some documentation and I’ll take care of it.

**Comment by ktnjared** [comment]
Just a heads up, the documentation is now available on Microsoft Docs: 
* [Publish An Extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension) 
([https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension))

Would love to see the extension in the Edge Addons catalog, especially with extension syncing being [slated for release this month](https://techcommunity.microsoft.com/t5/discussions/top-feedback-summary-for-march-11/m-p/1222906).

**Comment by aelisya** [comment]
I agree upload it on edgium Is a good idea

**Comment by da2x** [comment]
Challenge accepted.

**Comment by da2x** [comment]
🕥 “Microsoft is reviewing your submission right now​….”

If everything goes okay, it should appear on this page. Eventually.
https://microsoftedge.microsoft.com/addons/detail/abjhjmfkmdfggjomfpojjfcehhkambcc

**Comment by da2x** [comment]
It’s live at the above address. Please let me know of any issues @aelisya, @ktnjared.
