### ISSUE TITLE
Redirect loop on sciencealert.com

### ISSUE THREAD

**Issue by DIGIN4** [da2x/amp2html#16]
Using Firefox for Android, sciencealert.com keeps reloading instead of displaying the web page,  [this URL for example](https://www.sciencealert.com/the-new-coronavirus-could-circulate-forever-says-experts/amp)

**Comment by da2x** [comment]
This is a site-specific issue. The site redirects the canonical URL to their AMP URL when the User-Agent contains the string `Mobile`. This is the same problem as #13.

**Comment by da2x** [comment]
This should be fixed by f98dcb01aebe57d0f64505b9b3ee9b5b3ac35c02. It’ll be included in a future release (after I’ve had time for some more testing to make sure nothing breaks.)
