### ISSUE TITLE
Firefox prompts for "Access your data for all websites" permission

### ISSUE THREAD

**Issue by Caligatio** [da2x/amp2html#18]
I recently just started using this add-on and noticed that, on installation, it prompts for the "Access your data for all websites" permission.  I thought this was weird as it really should only need access to the relevant AMP domains.  I looked at the manifest.json and it appears that the extension is trying to do the right thing.

Admittedly I know very little about Firefox extensions but maybe the `content_scripts` is too broad?

**Comment by da2x** [comment]
No, it isn't  too broad.

AMP are published on the publishers websites. AMP Caches may cache them but you'll still frequently encounter AMP documents served dirrctly from the publisher's website.
