### ISSUE TITLE
[Question] Permissions on Firefox Add-Ons Store

### ISSUE THREAD

**Issue by exprez135** [da2x/amp2html#20]
Hello! Thank you for the extension and your work. I had a quick question about the permissions needed for the Firefox Add-On. At the moment it requests access to data for all websites. Is this needed, or could the permissions be restricted to the specific domains which serve AMP content?

**Comment by da2x** [comment]
> Is this needed, or could the permissions be restricted to the specific domains which serve AMP content?

*Any* domain can host AMP content. Publishers must host AMP on their domains. E.g. Twitter links to the publisher's AMP page on their domain and not an AMP Cache (like Google's or Bing's.)
