### ISSUE TITLE
[Suggestion] Create a userscript version

### ISSUE THREAD

**Issue by MPeti1** [da2x/amp2html#21]
I've been using the (normal) extension on Firefox for a while already, but I was wondering if you could make a Userscript version of it.

Since not all pages use AMP (and actually it's relatively rare among the sites I usually visit), I think it's not very efficient to keep the extension loaded at all times, and run it's scripts on every page load. With Userscipts, you can specify for which URL's should your script run

You might think that it's not worth the hassle, because this plugin does not do complex things, but I think that's why it would be easy to port, and what really matters is when is the script executed, and how much memory will it use.
Also, porting only this extension might not lower the load on browsers much, but I want to contact the devs of more extensions to make a Userscript version.

**Comment by da2x** [comment]
You can test it and let me know how it goes. The relevant bits are in [amp2html.js](https://github.com/da2x/amp2html/blob/master/scripts/amp2html.js). It should just work. You can benchmark it too, if you like. In my testing, sneezing will impact your wifi speed and thereby the pageload speed more than this script.

The [URL remapping](https://github.com/da2x/amp2html/blob/master/scripts/redirector.js) can only be done from an extension, however. That is probably the most active component of this extension.

**Comment by MPeti1** [comment]
> In my testing, sneezing will impact your wifi speed and thereby the pageload speed more than this script.

haha, I said that this one itself will not have much improvement

> The [URL remapping](https://github.com/da2x/amp2html/blob/master/scripts/redirector.js) can only be done from an extension, however. That is probably the most active component of this extension.

Well, then it's almost pointless to port it over there. But which part do you mean exactly, that it can only be done from an extension?
