### ISSUE TITLE
Mobile redirect backwards navigation freezes

### ISSUE THREAD

**Issue by danialasghar** [da2x/amp2html#29]
Hello, installed this on the latest Iceraven mobile build. 

Noticed the following issue:
The extension correctly redirects away from the amp page... unfortunately when navigation backwards it goes to a white unactionable stock amp page. 

Not sure if it can addressed it any manner or not but thought I'd report

**Comment by da2x** [comment]
Hi, do you have an example page? Where did you get the link? How did you open it? E.g. was it an AMP link opened from another app? or a web link pointing to an AMP page?

**Comment by danialasghar** [comment]
Sorry about that I was mistaken ... it seems to be working after retesting it.
