### ISSUE TITLE
It does not seem to work for this page

### ISSUE THREAD

**Issue by andreicristianpetcu** [da2x/amp2html#3]
Hi!

Great addon! Thank you!
It does not seem to work on this page https://newsstand.google.com/articles/CAIiEBXqZGzjExe8biDc0CDUuJ0qGQgEKhAIACoHCAow9935CjCe0eYCMNLmzAU

Thank you again!
Andrei

**Comment by da2x** [comment]
That page isn’t an AMP page (must be either `<html … ⚡>` or `<html … amp>`) so this extension won’t do any good there. It seems to be a Google-page with another page embedded inside an iframe. Seems to be a specific solution that I’ve only seen used on Newsstand.

Thank you for your report and your interest!

Please do report any other webpage you come across that don’t redirect properly. I’d like to (un)support every AMP page out there. 😄 I think the compatibility in the latest version is is pretty good, though.

**Comment by andreicristianpetcu** [comment]
Ahhh, I see. Sorry for the confusion. I will report future AMP misses if I bump into them. :)
