### ISSUE TITLE
Does not work with Google Amp on Fennec/Firefox Mobile

### ISSUE THREAD

**Issue by NobleUplift** [da2x/amp2html#5]
If I Google search anything on Firefox mobile with this addon installed, it does not redirect away from the AMP article. I can add screenshots/Firefox version if you need them.

**Comment by da2x** [comment]
Could you please provide a sample URL?

**Comment by da2x** [comment]
Ah. Google disregards their own pseudo-standard. I’ll find a work-around.

**Comment by da2x** [comment]
Resolved by commit 74d9effed4bf37a05d5c8ff755f464f4d9523390. New release within a few days.

**Comment by NobleUplift** [comment]
In the time it took me to remember what I searched for and sync a tab from my device to copy here, you discovered the source of the issue and committed a fix.

That was amazing.

**Comment by da2x** [comment]
If you force-update your extensions, it should also update on your device. 🧙

**Comment by da2x** [comment]
So the fix isn’t perfect, and you sometimes have to reload the tab for it to work. I’ve tried a few different solutions, but they all suffer from the same timing issue. I’d spend more time figuring this out, but Google have given indications that they’ll be [replacing](https://amphtml.wordpress.com/2018/01/09/improving-urls-for-amp-pages/amp/) this iframe system soon.

**Comment by NobleUplift** [comment]
I was going to update this post yesterday to relay much the same message. Is the issue worth reopening?

**Comment by da2x** [comment]
So Google has changed how this works two times in the last month. I’m waiting for this to stabilize.

**Comment by da2x** [comment]
Commit 77b25d9945 (included in [version 1.4.1](https://github.com/da2x/amp2html/releases/tag/v1.4.1)) introduced an ugly fix for this.
