### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by krathalan** [da2x/amp2html#8]
It would be nice if Redirect AMP to HTML had an official privacy policy on https://addons.mozilla.org. Given the nature of the addon and the fact that it's free and open source, I'm assuming the addon does not collect and/or send data to any server.

I even wrote a policy for you if you'd like to copy/paste it:
Redirect AMP to HTML does not collect or send data to any server.

**Comment by da2x** [comment]
The default policy on Mozilla Add-Ons is no data collection unless there is a privacy policy. I’ll add one with the next option regardless.

**Comment by da2x** [comment]
This will be in place for the next version.
