### ISSUE TITLE
CloudFlare AMP cache

### ISSUE THREAD

**Issue by crssi** [da2x/amp2html#9]
https://www.amp.cloudflare.com

Cheers

**Comment by da2x** [comment]
Support for Cloudflare AMP Cache was implemented as part of 5746481ee96d835a2502af9db564397838ba5467.

Support for Cloudflare AML out-out cookie was implemented in 03896adc52236e8603a2729f83ced9c61c140f21.

**Comment by da2x** [comment]
Thanks for notifying me, @crssi! I’ll test this for a few days before publishing an updated version. You can download the master branch and run it from about:debugging in Firefox if you’d like to test.
